#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# fixes this: https://talk.jekyllrb.com/t/error-your-site-could-not-be-built-no-repo-name-found/5688
repository: cooked/cooked.github.io

# https://jekyllrb.com/docs/plugins/installation/
plugins:
- jekyll-remote-theme # github remote themes
- jekyll-toc
- jekyll-archives
- jekyll-leaflet
#- jekyll-maps

exclude:
- '*.sh'
- '.devcontainer'
- '*.code-workspace'
- 'Gemfile*'

jekyll-archives:
  enabled: [year, month, tags]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
 
#maps:
#  google:
#    api_key: AIzaSyDzn_BBHyTBPqXoSNlu39u5vrYo5P2qLqg