# https://github.com/mmistakes/minimal-mistakes#remote-theme-method
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# fixes this: https://talk.jekyllrb.com/t/error-your-site-could-not-be-built-no-repo-name-found/5688
repository: cooked/cooked.github.io

title: ""
description: A Quarter To Seven
logo: "/assets/img/aqts_logo_block.png"

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
- _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
- '*.sh'
- '.devcontainer'
- '*.code-workspace'
- 'Gemfile*'
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://jekyllrb.com/docs/plugins/installation/
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
#- jekyll-last-modified-at
#- jekyll-leaflet
#- jekyll-target-blank # https://github.com/keithmifsud/jekyll-target-blank
#- jekyll-google-photos
#- jekyll-maps

jekyll-archives:
  enabled: [year, month, tags]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      #author_profile: true
      #read_time: true
      comments: true
      share: false
      related: true
      toc: true
      toc_label: "Contents"
      toc_icon: "none"
      toc_sticky: true

      sidebar:
        nav: "docs"
      header:
        teaser: /assets/img/fallback-layout.jpg

analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'G-VG004BYMTP' # 'UA-1061116-2'
    anonymize_ip: false # default

#google_site_verification: "yourVerificationCode"

author:
  name: "A Quarter to Seven"
  avatar: "/assets/images/bio-photo.jpg"
  #bio: "I am an **amazing** person." # Note: Markdown is allowed
  #location: "Somewhere"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/stefaniiino"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
