remote_theme: "andrewbanchich/forty-jekyll-theme"

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cooked
#gitlab_url: https://gitlab.com/andrewbanchich
instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
#markdown: kramdown

#sass:
#  style: compressed
